module.exports = {
  content: ['./js/**/*.{ts,js}', './templates/**/*.twig'],
  darkMode: 'class', // false or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [require('@tailwindcss/typography'), require('daisyui')],
  daisyui: {
    themes: [
      {
        solawiLight: {
          primary: '#82B440',
          'primary-focus': '#659724',
          'primary-content': '#ffffff',
          secondary: '#338F55',
          'secondary-focus': '#1C783E',
          'secondary-content': '#ffffff',
          accent: '#DAAE08',
          'accent-focus': '#B18B00',
          'accent-content': '#ffffff',
          neutral: '#82B440',
          'neutral-focus': '#2a2e37',
          'neutral-content': '#1f2937',
          'base-100': '#ffffff',
          'base-200': '#f9fafb',
          'base-300': '#d1d5db',
          'base-content': '#1f2937',
          info: '#2094f3',
          success: '#009485',
          warning: '#ff9900',
          error: '#ff5724',
        },
      },
      {
        solawiDark: {
          primary: '#82B440',
          'primary-focus': '#659724',
          'primary-content': '#ffffff',
          secondary: '#338F55',
          'secondary-focus': '#1C783E',
          'secondary-content': '#ffffff',
          accent: '#DAAE08',
          'accent-focus': '#B18B00',
          'accent-content': '#ffffff',
          neutral: '#338F55',
          'neutral-focus': '#2a2e37',
          'neutral-content': '#ffffff',
          'base-100': '#3D4451',
          'base-200': '#2A2E37',
          'base-300': '#16181D',
          'base-content': '#EBECF0',
          info: '#66C7FF',
          success: '#87D039',
          warning: '#E2D562',
          error: '#FF6F6F',
        },
      },
      'light',
      'dark',
    ],
  },
};
